/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypdfgenerator;

import functionalities.ImagetoPDF;
import java.io.File;
import java.io.FileNotFoundException;
import java.net.MalformedURLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author Dhrit pc
 */
public class ImageToPdf extends javax.swing.JInternalFrame {

    DefaultListModel<String> listModel = new DefaultListModel<String>();
    private static String filePath = null;
    ArrayList<File> sourceFiles = new ArrayList<>(); 
    File destFile = null;
    File sourceFile = null;
    int flag = 0;
    //int index = 0;
    /**
     * Creates new form ImageToPdf
     */
    public ImageToPdf() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        sourceTextFld = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList<String>(listModel);
        destTextFld = new javax.swing.JTextField();
        convertBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        moveDownBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        sourceFliBtn = new javax.swing.JButton();
        destFileBtn = new javax.swing.JButton();
        moveUpBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("jCheckBoxMenuItem3");

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 2, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dhrit pc\\Documents\\NetBeansProjects\\TestImage\\src\\main\\java\\mypdfgenerator\\20201127_002905.png")); // NOI18N
        jLabel1.setText("Image  to  PDF");

        jScrollPane1.setViewportView(list);

        convertBtn.setFont(new java.awt.Font("Segoe UI Symbol", 3, 24)); // NOI18N
        convertBtn.setIcon(new javax.swing.ImageIcon("D:\\Project images and icons\\must_have_icon_set\\Next\\Next_32x32.png")); // NOI18N
        convertBtn.setText("Convert");
        convertBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                convertBtnMouseClicked(evt);
            }
        });

        backBtn.setFont(new java.awt.Font("Segoe UI Symbol", 3, 24)); // NOI18N
        backBtn.setIcon(new javax.swing.ImageIcon("D:\\Project images and icons\\must_have_icon_set\\Previous\\Previous_32x32.png")); // NOI18N
        backBtn.setText("Back");
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 3, 24)); // NOI18N
        jLabel2.setText("Destination File");

        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 3, 24)); // NOI18N
        jLabel3.setText("Source File");

        moveDownBtn.setIcon(new javax.swing.ImageIcon("D:\\Project images and icons\\must_have_icon_set\\Stock Index Down\\Stock Index Down_24x24.png")); // NOI18N
        moveDownBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moveDownBtnMouseClicked(evt);
            }
        });

        removeBtn.setIcon(new javax.swing.ImageIcon("D:\\Project images and icons\\must_have_icon_set\\Remove\\Remove_24x24.png")); // NOI18N
        removeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeBtnMouseClicked(evt);
            }
        });

        sourceFliBtn.setIcon(new javax.swing.ImageIcon("D:\\Project images and icons\\must_have_icon_set\\Open\\Open_24x24.png")); // NOI18N
        sourceFliBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sourceFliBtnMouseClicked(evt);
            }
        });

        destFileBtn.setIcon(new javax.swing.ImageIcon("D:\\Project images and icons\\must_have_icon_set\\Open\\Open_24x24.png")); // NOI18N
        destFileBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                destFileBtnMouseClicked(evt);
            }
        });

        moveUpBtn.setIcon(new javax.swing.ImageIcon("D:\\Project images and icons\\must_have_icon_set\\Stock Index Up\\Stock Index Up_24x24.png")); // NOI18N
        moveUpBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moveUpBtnMouseClicked(evt);
            }
        });

        addBtn.setIcon(new javax.swing.ImageIcon("D:\\Project images and icons\\must_have_icon_set\\Edit\\Edit_24x24.png")); // NOI18N
        addBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(convertBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(161, 161, 161)
                                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(sourceTextFld, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                    .addComponent(sourceFliBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(removeBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(moveUpBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(moveDownBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(addBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(destTextFld, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(destFileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(357, 357, 357)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sourceTextFld, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sourceFliBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(moveUpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(moveDownBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(removeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(destTextFld, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(destFileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(backBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(convertBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void convertBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convertBtnMouseClicked
        if(flag == 0){
            destFile = new File(destTextFld.getText());
        }
//        String extension = sourceFile.getName();
//        destFile = new File(destFile.getPath() + File.separator + extension + ".pdf");
        try {
            ImagetoPDF.generatePdf( sourceFiles, destFile);
            new ScreenOpening(new ThankuScreen(destFile.getPath()));
        } catch (MalformedURLException ex) {
            Logger.getLogger(ImageToPdf.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ImageToPdf.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_convertBtnMouseClicked

    private void backBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseClicked
        
        new ScreenOpening(new OptionsScreen());
    }//GEN-LAST:event_backBtnMouseClicked

    private void sourceFliBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sourceFliBtnMouseClicked
        
        sourceFile = ImageToPdf.getPath(JFileChooser.FILES_ONLY);
        sourceTextFld.setText(sourceFile.getPath());
        destTextFld.setText(sourceFile.getPath().substring(0, sourceFile.getPath().lastIndexOf(".pdf")+1)+".pdf");
    }//GEN-LAST:event_sourceFliBtnMouseClicked

    private void destFileBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_destFileBtnMouseClicked
        
        flag = 1;
        destFile = ImageToPdf.getPath(JFileChooser.DIRECTORIES_ONLY);
        destTextFld.setText(destFile.getPath());
        String extension = sourceFile.getName();//"AAPPword1";
        destFile = new File(destFile.getPath() + File.separator + extension + ".pdf");
    }//GEN-LAST:event_destFileBtnMouseClicked

    private void addBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseClicked
        
        if(sourceTextFld.getText().isEmpty()){
            //popup
            JOptionPane.showMessageDialog(new JFrame(),"Error, First Enter any item","Alert",JOptionPane.WARNING_MESSAGE);
        }
        else{
            listModel.addElement(sourceTextFld.getText());
            sourceFiles.add(sourceFile);
            sourceTextFld.setText(null);
            sourceTextFld.grabFocus();
        }
    }//GEN-LAST:event_addBtnMouseClicked

    private void removeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeBtnMouseClicked
       
        listModel.remove(listModel.size() - 1);
        sourceFiles.remove(sourceFiles.size() - 1);
    }//GEN-LAST:event_removeBtnMouseClicked

    private void moveUpBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveUpBtnMouseClicked
        
        File tempFile = sourceFiles.get(list.getSelectedIndex()-1);
        sourceFiles.set(list.getSelectedIndex()-1, sourceFiles.get(list.getSelectedIndex()));
        sourceFiles.set(list.getSelectedIndex(), tempFile);
        
        String temp = listModel.getElementAt(list.getSelectedIndex()-1);
        listModel.set(list.getSelectedIndex()-1, list.getSelectedValue());
        listModel.set(list.getSelectedIndex(), temp);
    }//GEN-LAST:event_moveUpBtnMouseClicked

    private void moveDownBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveDownBtnMouseClicked
        
        File tempFile = sourceFiles.get(list.getSelectedIndex()+1);
        sourceFiles.set(list.getSelectedIndex()+1, sourceFiles.get(list.getSelectedIndex()));
        sourceFiles.set(list.getSelectedIndex(), tempFile);
        
        String temp = listModel.getElementAt(list.getSelectedIndex()+1);
        listModel.set(list.getSelectedIndex()+1, list.getSelectedValue());
        listModel.set(list.getSelectedIndex(), temp);
    }//GEN-LAST:event_moveDownBtnMouseClicked

    public static File getPath(int choice) {
    	
    	
    	JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(choice);
        int returnValue = fileChooser.showOpenDialog(null);
        
        File selectedFile = null;
        if (returnValue == JFileChooser.APPROVE_OPTION) 
        {
            selectedFile = fileChooser.getSelectedFile();
           
        }
        
    	return selectedFile;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton convertBtn;
    private javax.swing.JButton destFileBtn;
    private javax.swing.JTextField destTextFld;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> list;
    private javax.swing.JButton moveDownBtn;
    private javax.swing.JButton moveUpBtn;
    private javax.swing.JButton removeBtn;
    private javax.swing.JButton sourceFliBtn;
    private javax.swing.JTextField sourceTextFld;
    // End of variables declaration//GEN-END:variables
}
