/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypdfgenerator;

import java.io.File;
/**
 *
 * @author Dhrit pc
 */
public class OptionsScreen extends javax.swing.JInternalFrame {

    /**
     * Creates new form OptionsScreen
     */
    public OptionsScreen() {
        File f = new File(".");
        System.out.println( f.getAbsolutePath()+"====>"+"||||"+getClass().getResource("20201124_211249.png"));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        imageToPdfBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        pdfSplitterBtn = new javax.swing.JButton();
        textToPdfBtn = new javax.swing.JButton();
        wordToPdfBtn = new javax.swing.JButton();
        pdfMergerBtn = new javax.swing.JButton();
        optionLabel = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        imageToPdfBtn.setFont(new java.awt.Font("Segoe UI Symbol", 3, 24)); // NOI18N
        imageToPdfBtn.setText("Image to PDF");
        imageToPdfBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageToPdfBtnMouseClicked(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI Symbol", 3, 24)); // NOI18N
        jButton2.setText("HTML to PDF");

        pdfSplitterBtn.setFont(new java.awt.Font("Segoe UI Symbol", 3, 24)); // NOI18N
        pdfSplitterBtn.setText("PDF Splitter");
        pdfSplitterBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pdfSplitterBtnMouseClicked(evt);
            }
        });

        textToPdfBtn.setFont(new java.awt.Font("Segoe UI Symbol", 3, 24)); // NOI18N
        textToPdfBtn.setText("Text to PDF");
        textToPdfBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textToPdfBtnMouseClicked(evt);
            }
        });

        wordToPdfBtn.setFont(new java.awt.Font("Segoe UI Symbol", 3, 24)); // NOI18N
        wordToPdfBtn.setText("Word to PDF");
        wordToPdfBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wordToPdfBtnMouseClicked(evt);
            }
        });

        pdfMergerBtn.setFont(new java.awt.Font("Segoe UI Symbol", 3, 24)); // NOI18N
        pdfMergerBtn.setText("PDF Merger");
        pdfMergerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pdfMergerBtnMouseClicked(evt);
            }
        });

        optionLabel.setFont(new java.awt.Font("Segoe UI Symbol", 2, 36)); // NOI18N
        optionLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dhrit pc\\Documents\\NetBeansProjects\\TestImage\\src\\main\\java\\mypdfgenerator\\20201124_211249.png")); // NOI18N
        optionLabel.setText("OPTIONS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(267, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(wordToPdfBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textToPdfBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(imageToPdfBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pdfMergerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pdfSplitterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(328, 328, 328))
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(optionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(optionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imageToPdfBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textToPdfBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wordToPdfBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pdfMergerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pdfSplitterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textToPdfBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textToPdfBtnMouseClicked

        new ScreenOpening(new TexttoPdf());
    }//GEN-LAST:event_textToPdfBtnMouseClicked

    private void wordToPdfBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wordToPdfBtnMouseClicked
       
        new ScreenOpening(new WordToPdf());
    }//GEN-LAST:event_wordToPdfBtnMouseClicked

    private void imageToPdfBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageToPdfBtnMouseClicked
        
        new ScreenOpening(new ImageToPdf());
    }//GEN-LAST:event_imageToPdfBtnMouseClicked

    private void pdfMergerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pdfMergerBtnMouseClicked
        
        new ScreenOpening(new PdfToPdf());
    }//GEN-LAST:event_pdfMergerBtnMouseClicked

    private void pdfSplitterBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pdfSplitterBtnMouseClicked
        
        new ScreenOpening(new PdfSplitter());
    }//GEN-LAST:event_pdfSplitterBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton imageToPdfBtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JLabel optionLabel;
    private javax.swing.JButton pdfMergerBtn;
    private javax.swing.JButton pdfSplitterBtn;
    private javax.swing.JButton textToPdfBtn;
    private javax.swing.JButton wordToPdfBtn;
    // End of variables declaration//GEN-END:variables
}
