/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypdfgenerator;

import functionalities.PdfSpliter;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author Dhrit pc
 */
public class PdfSplitter extends javax.swing.JInternalFrame {

    int flag = 0;
    File sourceFile = null;
    public static File destFile = null;
    /**
     * Creates new form PdfSplitter
     */
    public PdfSplitter() {
        initComponents();
//        ImageIcon image = new ImageIcon(getClass().getResource("/ImagesandLabels/pdf-splitter-5ae380d68e1b6e0037e1fc11.png"));
//        image=new ImageIcon(image.getImage().getScaledInstance(300, 190, Image.SCALE_DEFAULT));
//            
//        headingLabel.setIcon(image);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        headingLabel = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        sourceTextFld = new javax.swing.JTextField();
        pageNumFld = new javax.swing.JTextField();
        destTextFld = new javax.swing.JTextField();
        exampleTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        destFileBtn = new javax.swing.JButton();
        sourceFileBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        convertBtn = new javax.swing.JButton();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        headingLabel.setFont(new java.awt.Font("Segoe UI Symbol", 2, 36)); // NOI18N
        headingLabel.setIcon(new javax.swing.ImageIcon("D:\\Project images and icons\\WhatsApp Image 2020-12-16 at 09.00.58.jpeg")); // NOI18N

        sourceTextFld.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N

        pageNumFld.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N

        destTextFld.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N

        exampleTextField.setEditable(false);
        exampleTextField.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        exampleTextField.setText("1 , 2 , 5 , 7 , 9 - 20 , 30 - 40 , 6 , 11 ");
        exampleTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exampleTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 3, 24)); // NOI18N
        jLabel1.setText("Source File");

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 3, 24)); // NOI18N
        jLabel2.setText("Example");

        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 3, 24)); // NOI18N
        jLabel3.setText("Enter Pages");

        jLabel4.setFont(new java.awt.Font("Segoe UI Symbol", 3, 24)); // NOI18N
        jLabel4.setText("Destination File");

        destFileBtn.setIcon(new javax.swing.ImageIcon("D:\\Project images and icons\\must_have_icon_set\\Open\\Open_24x24.png")); // NOI18N
        destFileBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                destFileBtnMouseClicked(evt);
            }
        });

        sourceFileBtn.setIcon(new javax.swing.ImageIcon("D:\\Project images and icons\\must_have_icon_set\\Open\\Open_24x24.png")); // NOI18N
        sourceFileBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sourceFileBtnMouseClicked(evt);
            }
        });

        backBtn.setFont(new java.awt.Font("Segoe UI Symbol", 3, 24)); // NOI18N
        backBtn.setIcon(new javax.swing.ImageIcon("D:\\Project images and icons\\must_have_icon_set\\Previous\\Previous_32x32.png")); // NOI18N
        backBtn.setText("Back");
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnMouseClicked(evt);
            }
        });

        convertBtn.setFont(new java.awt.Font("Segoe UI Symbol", 3, 24)); // NOI18N
        convertBtn.setIcon(new javax.swing.ImageIcon("D:\\Project images and icons\\must_have_icon_set\\Next\\Next_32x32.png")); // NOI18N
        convertBtn.setText("Convert");
        convertBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                convertBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(convertBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sourceTextFld, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pageNumFld, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(destTextFld, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exampleTextField, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sourceFileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(destFileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(200, 200, 200))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(headingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(388, 388, 388))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sourceTextFld, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sourceFileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exampleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pageNumFld, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(destTextFld, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destFileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(convertBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exampleTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exampleTextFieldActionPerformed
        
    }//GEN-LAST:event_exampleTextFieldActionPerformed

    private void convertBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convertBtnMouseClicked
        if(flag == 0){
            destFile = new File(destTextFld.getText());
        }
        try {
            System.out.println(pageNumFld.getText());
            String[] pages = pageNumFld.getText().split(",");
//            String extension = sourceFile.getName();
//            destFile = new File(destFile.getPath() + File.separator + extension + ".pdf" );
            PdfSpliter.generatePdf(sourceFile, destFile , pages);
            new ScreenOpening(new ThankuScreen(destFile.getPath()));
        } catch (IOException ex) {
            Logger.getLogger(PdfSplitter.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_convertBtnMouseClicked

    private void backBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseClicked
        
        new ScreenOpening(new OptionsScreen());
    }//GEN-LAST:event_backBtnMouseClicked

    private void sourceFileBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sourceFileBtnMouseClicked
        
        sourceFile = PdfSplitter.getPath(JFileChooser.FILES_ONLY);
        sourceTextFld.setText(sourceFile.getPath());
        destTextFld.setText(sourceFile.getPath().substring(0, sourceFile.getPath().lastIndexOf(".pdf")+1)+".pdf");
    }//GEN-LAST:event_sourceFileBtnMouseClicked

    private void destFileBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_destFileBtnMouseClicked
       
        flag = 1;
        destFile = PdfSplitter.getPath(JFileChooser.DIRECTORIES_ONLY);
        //destTextFld.removeAll();
        destTextFld.setText(destFile.getPath());
        String extension = sourceFile.getName();//"AAPPword1";
        destFile = new File(destFile.getPath() + File.separator + extension + ".pdf");
    }//GEN-LAST:event_destFileBtnMouseClicked
    
    public static File getPath(int choice) {
    	
    	JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(choice);
        int returnValue = fileChooser.showOpenDialog(null);
        
        File selectedFile = null;
        if (returnValue == JFileChooser.APPROVE_OPTION) 
        {
            selectedFile = fileChooser.getSelectedFile();
           
        }
        
    	return selectedFile;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton convertBtn;
    private javax.swing.JButton destFileBtn;
    private javax.swing.JTextField destTextFld;
    private javax.swing.JTextField exampleTextField;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField pageNumFld;
    private javax.swing.JButton sourceFileBtn;
    private javax.swing.JTextField sourceTextFld;
    // End of variables declaration//GEN-END:variables
}
