/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypdfgenerator;

import functionalities.TexttoPDF;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static mypdfgenerator.PdfSplitter.destFile;

/**
 *
 * @author Dhrit pc
 */
public class TexttoPdf extends javax.swing.JInternalFrame {

    DefaultListModel<String> listModel = new DefaultListModel<String>();
    private static String filePath = null;
    File sourceFile = null;
    File destFile = null;
    int flag = 0;
    /**
     * Creates new form TexttoPdf
     */
    public TexttoPdf() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem4 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem5 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem6 = new javax.swing.JCheckBoxMenuItem();
        progressBar = new javax.swing.JProgressBar();
        sourceTextFld = new javax.swing.JTextField();
        destTextFld = new javax.swing.JTextField();
        sourceFileBtn = new javax.swing.JButton();
        destFileBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        convertBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("jCheckBoxMenuItem3");

        jMenuItem1.setText("jMenuItem1");

        jCheckBoxMenuItem4.setSelected(true);
        jCheckBoxMenuItem4.setText("jCheckBoxMenuItem4");

        jCheckBoxMenuItem5.setSelected(true);
        jCheckBoxMenuItem5.setText("jCheckBoxMenuItem5");

        jCheckBoxMenuItem6.setSelected(true);
        jCheckBoxMenuItem6.setText("jCheckBoxMenuItem6");

        progressBar.setBackground(new java.awt.Color(0, 0, 255));
        progressBar.setFont(new java.awt.Font("Segoe UI Symbol", 3, 18)); // NOI18N

        destTextFld.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                destTextFldMouseClicked(evt);
            }
        });

        sourceFileBtn.setIcon(new javax.swing.ImageIcon("D:\\Project images and icons\\must_have_icon_set\\Open\\Open_24x24.png")); // NOI18N
        sourceFileBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sourceFileBtnMouseClicked(evt);
            }
        });

        destFileBtn.setIcon(new javax.swing.ImageIcon("D:\\Project images and icons\\must_have_icon_set\\Open\\Open_24x24.png")); // NOI18N
        destFileBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                destFileBtnMouseClicked(evt);
            }
        });

        backBtn.setFont(new java.awt.Font("Segoe UI Symbol", 3, 24)); // NOI18N
        backBtn.setIcon(new javax.swing.ImageIcon("D:\\Project images and icons\\must_have_icon_set\\Previous\\Previous_32x32.png")); // NOI18N
        backBtn.setText("Back");
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnMouseClicked(evt);
            }
        });

        convertBtn.setFont(new java.awt.Font("Segoe UI Symbol", 3, 24)); // NOI18N
        convertBtn.setIcon(new javax.swing.ImageIcon("D:\\Project images and icons\\must_have_icon_set\\Next\\Next_32x32.png")); // NOI18N
        convertBtn.setText("Convert");
        convertBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                convertBtnMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 3, 24)); // NOI18N
        jLabel1.setText("Destination File");

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 3, 24)); // NOI18N
        jLabel2.setText("Source File");

        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 2, 36)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dhrit pc\\Documents\\NetBeansProjects\\TestImage\\src\\main\\java\\mypdfgenerator\\20201126_215518.png")); // NOI18N
        jLabel3.setText("Text  to  PDF");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(sourceTextFld, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(progressBar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(destTextFld)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(convertBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sourceFileBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(destFileBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(399, 399, 399)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sourceFileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sourceTextFld, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(129, 129, 129)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(destTextFld, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(destFileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(convertBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void convertBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convertBtnMouseClicked
        
        if(flag == 0){
            destFile = new File(destTextFld.getText());
        }
        //String extension = sourceFile.getName();//"AAPPtext1";
        //destFile = new File(destFile.getPath() + File.separator + extension + ".pdf");
        try {
            
            TexttoPDF.generatePdf(sourceFile, destFile , progressBar);
            new ScreenOpening(new ThankuScreen(destFile.getPath()));
        } catch (IOException ex) {
            Logger.getLogger(TexttoPdf.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_convertBtnMouseClicked

    private void backBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseClicked
        
        progressBar.setValue(0);
        new ScreenOpening(new OptionsScreen());
    }//GEN-LAST:event_backBtnMouseClicked

    private void sourceFileBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sourceFileBtnMouseClicked
        
        sourceFile = TexttoPdf.getPath(JFileChooser.FILES_ONLY);
        sourceTextFld.setText(sourceFile.getPath());
        destTextFld.setText(sourceFile.getPath().substring(0, sourceFile.getPath().lastIndexOf(".txt")+1)+".pdf");
        for(int i=0;i<=progressBar.getMaximum()*1000000;i++){
            
            progressBar.setValue(i/1000000);
        }
    }//GEN-LAST:event_sourceFileBtnMouseClicked

    private void destFileBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_destFileBtnMouseClicked
        flag = 1;
        destFile = TexttoPdf.getPath(JFileChooser.DIRECTORIES_ONLY);
        destTextFld.removeAll();
        destTextFld.setText(destFile.getPath());
        String extension = sourceFile.getName();//"AAPPword1";
        destFile = new File(destFile.getPath() + File.separator + extension + ".pdf");
       
    }//GEN-LAST:event_destFileBtnMouseClicked

    private void destTextFldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_destTextFldMouseClicked
        
        
    }//GEN-LAST:event_destTextFldMouseClicked

    public static File getPath(int choice) {
    	
    	
    	JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(choice);
        int returnValue = fileChooser.showOpenDialog(null);
        
        File selectedFile = null;
        if (returnValue == JFileChooser.APPROVE_OPTION) 
        {
            selectedFile = fileChooser.getSelectedFile();
           
        }
        
    	return selectedFile;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton convertBtn;
    private javax.swing.JButton destFileBtn;
    private javax.swing.JTextField destTextFld;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem4;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem5;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JButton sourceFileBtn;
    private javax.swing.JTextField sourceTextFld;
    // End of variables declaration//GEN-END:variables
}
