/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypdfgenerator;

import functionalities.WordtoPDF;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Dhrit pc
 */
public class WordToPdf extends javax.swing.JInternalFrame {

    DefaultListModel<String> listModel = new DefaultListModel<String>();
    private static String filePath = null;
    File sourceFile = null;
    File destFile = null;
    int flag = 0;
    /**
     * Creates new form WordToPdf
     */
    public WordToPdf() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jLabel1 = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        sourceTextFld = new javax.swing.JTextField();
        destTextFld = new javax.swing.JTextField();
        backBtn = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        destFileBtn = new javax.swing.JToggleButton();
        convertBtn = new javax.swing.JButton();
        sourceFileBtn = new javax.swing.JButton();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 2, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dhrit pc\\Documents\\NetBeansProjects\\TestImage\\src\\main\\java\\mypdfgenerator\\20201127_080145.png")); // NOI18N
        jLabel1.setText("Word  to  PDF");

        destTextFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destTextFldActionPerformed(evt);
            }
        });

        backBtn.setFont(new java.awt.Font("Segoe UI Symbol", 3, 24)); // NOI18N
        backBtn.setIcon(new javax.swing.ImageIcon("D:\\Project images and icons\\must_have_icon_set\\Previous\\Previous_32x32.png")); // NOI18N
        backBtn.setText("Back");
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 3, 24)); // NOI18N
        jLabel2.setText("Source File");

        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 3, 24)); // NOI18N
        jLabel3.setText("Destination File");

        destFileBtn.setIcon(new javax.swing.ImageIcon("D:\\Project images and icons\\must_have_icon_set\\Open\\Open_24x24.png")); // NOI18N
        destFileBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                destFileBtnMouseClicked(evt);
            }
        });

        convertBtn.setFont(new java.awt.Font("Segoe UI Symbol", 3, 24)); // NOI18N
        convertBtn.setIcon(new javax.swing.ImageIcon("D:\\Project images and icons\\must_have_icon_set\\Next\\Next_32x32.png")); // NOI18N
        convertBtn.setText("Convert");
        convertBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                convertBtnMouseClicked(evt);
            }
        });

        sourceFileBtn.setIcon(new javax.swing.ImageIcon("D:\\Project images and icons\\must_have_icon_set\\Open\\Open_24x24.png")); // NOI18N
        sourceFileBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sourceFileBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(364, 364, 364)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(sourceTextFld, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(convertBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(87, 87, 87)
                                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(destTextFld, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(destFileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sourceFileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(259, 259, 259))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sourceTextFld, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sourceFileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(destTextFld, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(destFileBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(backBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(convertBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void destTextFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destTextFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destTextFldActionPerformed

    private void backBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseClicked
       
        new ScreenOpening(new OptionsScreen());
    }//GEN-LAST:event_backBtnMouseClicked

    private void destFileBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_destFileBtnMouseClicked
        
        flag = 1;
        destFile = WordToPdf.getPath(JFileChooser.DIRECTORIES_ONLY);
        destTextFld.removeAll();
        destTextFld.setText(destFile.getPath());
        String extension = sourceFile.getName();//"AAPPword1";
        destFile = new File(destFile.getPath() + File.separator + extension + ".pdf");
    }//GEN-LAST:event_destFileBtnMouseClicked

    private void convertBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convertBtnMouseClicked
        if(flag == 0){
            destFile = new File(destTextFld.getText());
        }
//        String extension = sourceFile.getName();//"AAPPword1";
//        destFile = new File(destFile.getPath() + File.separator + extension + ".pdf");
        try {
            WordtoPDF.generatePdf(sourceFile, destFile);
            new ScreenOpening(new ThankuScreen(destFile.getPath()));
        } catch (IOException ex) {
            Logger.getLogger(WordToPdf.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_convertBtnMouseClicked

    private void sourceFileBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sourceFileBtnMouseClicked
        
        sourceFile = WordToPdf.getPath(JFileChooser.FILES_ONLY);
        sourceTextFld.setText(sourceFile.getPath());
        destTextFld.setText(sourceFile.getPath().substring(0, sourceFile.getPath().lastIndexOf(".docx")+1)+".pdf");
    }//GEN-LAST:event_sourceFileBtnMouseClicked

    public static File getPath(int choice) {
    	
    	
    	JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(choice);
        int returnValue = fileChooser.showOpenDialog(null);
        
        File selectedFile = null;
        if (returnValue == JFileChooser.APPROVE_OPTION) 
        {
            selectedFile = fileChooser.getSelectedFile();
           
        }
        
    	return selectedFile;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton backBtn;
    private javax.swing.JButton convertBtn;
    private javax.swing.JToggleButton destFileBtn;
    private javax.swing.JTextField destTextFld;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JButton sourceFileBtn;
    private javax.swing.JTextField sourceTextFld;
    // End of variables declaration//GEN-END:variables
}
